name: heise

on:
  workflow_dispatch:
#  push:
#    branches:
#      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alexanderwessel/calibre    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: publish-heise-to-dropbox
        shell: bash
        env:
            DROPBOX_PERSONAL_TOKEN: ${{ secrets.DROPBOX_PERSONAL_TOKEN }}
        run: |
            publish-heise-to-dropbox.sh