name: heise

on:
  workflow_dispatch:
#  push:
#    branches:
#      - "main"

jobs:
  build:
    runs-on: alexanderwessel/calibre
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
