on:
  schedule:
    - cron: '40 16 * * *'
    # min, hour (24h UTC), day of month, month, day of week 0-6 SUN-SAT
    # it needs up to 15 min to start    
  workflow_dispatch:
jobs:
  publish-heise:
    runs-on: ubuntu-latest
    container:
      image: linuxserver/calibre:latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: publish-heise-to-gdrive
        env:
            GDRIVE_ACCOUNT_BASE64: ${{ secrets.GDRIVE_ACCOUNT_BASE64 }}
        run: |
            bash publish-heise-to-gdrive.sh