on:
  workflow_dispatch:
#  push:
#    branches:
#      - "main"

jobs:
  publish-heise:
    runs-on: ubuntu-latest
    container:
      image: alexanderwessel/calibre    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: publish-heise-to-gdrive
        env:
            GDRIVE_ACCOUNT_BASE64: ${{ secrets.GDRIVE_ACCOUNT_BASE64 }}
        run: |
            bash publish-heise-to-gdrive.sh